env:
  global:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
  - CC_TEST_REPORTER_ID=

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
- gem update --system
- gem install bundler

install:
- bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

language: ruby
sudo: false
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
  fast_finish: true
  include:
  - rvm: 2.3.7
    gemfile: gemfiles/ruby_2.3.7.gemfile
  - rvm: 2.4.4
    gemfile: gemfiles/ruby_2.4.4.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/ruby_2.5.1.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/ruby_head.gemfile
  - rvm: jruby-9.2.0.0
    gemfile: gemfiles/jruby_9.2.0.0.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/jruby_head.gemfile
